config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|fr/ do
    resources :clients
    root 'pages#home'
    get '/search', to: 'clients#search'
    devise_for :users, path: '', path_names: { sign_in: 'login', sign_up: 'register', sign_out: 'logout', edit: 'profile' }
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :clients  

  before_destroy :must_not_refer_to_client

  private
    def must_not_refer_to_client
      unless line_items.empty?
        errors.add(:base, 'This category is being referenced by a client(s), either delete the client(s) first, or contact your administrator')
        throw :abort
      end
    end
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user
  belongs_to :category

  before_save { 
    self.email = email.downcase 
    self.first_name = first_name.downcase.capitalize!
    self.last_name = last_name.downcase.capitalize!
  }

  validates :first_name, :last_name, presence: true, length: { minimum: 2, maximum: 150 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :clients

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :full_name, presence: true, length: { minimum: 2, maximum: 70 }
  validates :organization, allow_blank: true, length: {minimum: 3, maximum: 70}, on: :update
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale
  before_action :configure_permitted_parameters, if: :devise_controller?

  def switch_locale(&action)
      I18n.with_locale(params[:locale] || I18n.default_locale, &action)
  end

  def default_url_options
      { locale: I18n.locale }
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :organization])
    devise_parameter_sanitizer.permit(:account_update, keys: [:full_name, :organization])
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  before_action :authenticate_user!, except: [:show]
  before_action :set_client, except: [:new, :create, :index, :search]
  before_action :set_category, only: [:new, :edit, :update, :index, :search]
  before_action :is_authorised, only: [:edit, :update, :destroy]

  def new
    @client = current_user.clients.build
  end

  def create
    @client = current_user.clients.build(client_params)
    if @client.save
      redirect_to clients_path, notice: "#{@client.first_name} has been added successfully"
    else
      # for dev mode to show all errors.
      redirect_to request.referrer, flash: { error: @client.errors.full_messages }
    end
  end

  def edit
  end

  def update
    if @client.update(client_params)
      flash[:notice] = "#{@client.first_name} has been updated successfully..."
    else
      flash[:alert] = "Hmmm...can not process this action."
    end
    redirect_to request.referrer
  end

  def show
  end

  def index
    @client = Client.order(:created_at)
  end

  def destroy
    @client.destroy
    redirect_to clients_path, notice: "Your client has been deleted successfully."
  end

  def search
    # In case no categories are provided, make it nil
    @category = Category.find(params[:category]) if params[:category].present?

    # get all clients in db with templated condition, and compare it to arguements passed in the url
    #@clients = Client.where("active = ? AND clients.first_name ILIKE ? AND category_id = ?", true, "%#{params[:f]}%", params[:category]) 

    # Refactoring code based on https://apidock.com/rails/ActiveRecord/QueryMethods/where
    @s = params[:s]
    @min = params[:min]
    @max = params[:max]
    @sort = params[:sort].present? ? params[:sort] : "revenue desc"

    search_condition = []
    search_condition[0] = "clients.active = true"

    # first condition - the first value, index 0 of the array will be a template, and second will check if @s is not blank and add search_condition into index 0, then push and create another value in the array
    if !@s.blank?
      search_condition[0] += ' AND clients.first_name ILIKE ?'
      search_condition.push "#{@s}"
      # keep adding elements into the array
    end
    
    # second condition
    if !params[:category].blank?
      search_condition[0] += ' AND category_id = ?'
      search_condition.push params[:category]
      # keep adding elements into the array, to create the third value in the array.
    end
    
    if !params[:min].blank?
      search_condition[0] += ' AND revenue >= ?'
      search_condition.push @min
      # keep value of the min.
    end

    if !params[:max].blank?
      search_condition[0] += ' AND revenue <= ?'
      search_condition.push @max
      # keep value of the max.
    end

    # we join the revenue
    @clients = current_user.clients.select("clients.id, clients.first_name, clients.last_name, clients.email, 
                              clients.category_id, clients.created_at, clients.revenue, 
                              clients.active").where(search_condition).order(@sort)

  end

 
  private
    def set_client
      @client = Client.find(params[:id])
    end

    def set_category
      @categories = Category.all
    end

    def is_authorised
      redirect_to root_path, alert: "Hmm..not authorized for this action" unless current_user.id == @client.user_id
    end

    def client_params
      params.require(:client).permit(:first_name, :last_name, :email, :active, :revenue, :category_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(status)
    status ? 'text-success' : 'text-danger'
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
  def client_full_name(client)
    [client.first_name, client.last_name].join(' ')
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/clients/edit.html.erb
<div class="row align-items-center pt-5 pb-5 pb-lg-3 mt-3">
  <!-- Card START -->
  <div class="col-lg-10 col-xs-12 mx-auto">
    <h1>Edit Your Client</h1>
    <p class="mb-4">Let's edit your Client.</p>
     
    <div class="card mb-4">
      <div class="card-body">
        <%= form_for @client, html: {class: 'row g-3'} do |f| %>

          <div class="col-md-6">
            <label class="form-label">Client first name</label>
            <%= f.text_field :first_name, autocomplete: 'first-name', class: 'form-control' %>
          </div>

          <div class="col-md-6">
            <label class="form-label">Client last name</label>
            <%= f.text_field :last_name, autocomplete: 'last-name', class: 'form-control' %>
          </div>
          
          <div class="col-md-8">
            <label class="form-label">Client email</label>
            <%= f.text_field :email, autocomplete: 'email', class: 'form-control' %>
          </div>

          <div class="col-md-4">
            <label class="form-label">Category</label>
            <%= f.select(:category_id, options_for_select(@categories.map{ |c| [c.name, c.id] },
            selected: @client.category_id), {}, {class: 'form-select rounded'}) %>
          </div>

          <div class="col-md-6">
            <label class="form-label">Total Revenue From Client</label>
            <%= f.number_field :revenue, autocomplete: 'revenue', class: 'form-control' %>
          </div>

          <div class="col-md-6 p-2 mr-2 mt-auto">
            <div class="form-check pl-3">
              <%= f.check_box :active, { class: 'form-check-input' } %>
              <label class="form-check-label">
                <%= @client.active ? 'Uncheck to Deactivate' : 'Check to Activate' %>
              </label>
            </div>
          </div>

          <%= f.submit "Update Client", class: 'btn btn-sm btn-primary mb-0' %>
          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/clients/index.html.erb
<div class="row align-items-center pt-5 mt-3">
  <div class="col-md-10 mx-auto">
    <h1><%= t('.your_clients') %></h1>
    <p><%= t('.clients_greeting_html') %></p>
    
      <div class="card-body">
        
        <% if current_user.clients.empty? %>

          <div class="text-center">
            
            <%= link_to new_client_path, class: 'border-0 bg-transparent' do %>
              <i class="add-client-icon display-1 text-muted bi bi-plus-circle-fill"></i>
            <% end %>

            <h4 class="mt-2 mb-3 text-body">You don't have any clients.</h4>

            <%= link_to "Add your first client",  new_client_path, class: 'btn btn-primary' %>

          </div>

        <% else %>

          <div class="row g-4">
            <div class="col-lg-8 vstack gap-4">
              <div class="card bg-primary">
                <div class="card-header border-0 pb-0">
                  <h5 class="card-title text-light">Filter by category</h5>
                </div>
                <%= render "shared/categories" %>
                <div class="card-body bg-light">
                  <div class="table-responsive-lg no-border">
                    <table class="table">
                      <thead>
                        <tr>
                          <th class="text-nowrap" scope="col">First Name</th>
                          <th class="text-nowrap" scope="col">Last Name</th>
                          <th class="text-nowrap" scope="col">Email</th>
                          <th class="text-nowrap" scope="col">Category</th>
                          <th class="text-nowrap" scope="col">Date Added</th>
                          <th class="text-nowrap" scope="col">Total Revenue</th>
                          <th class="text-nowrap" scope="col">Status</th>
                          <th class="text-nowrap" scope="col">Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% cache current_user.clients do %>
                          <% current_user.clients.sort.each do |c| %>
                            <% cache c do %>
                            <tr>
                              <td class="text-nowrap"><%= link_to c.first_name, client_path(c) %></td>
                              
                              <td class="text-nowrap"><%= c.last_name %></td>
                              <td class="text-nowrap"><%= c.email %></td>
                               <td class="text-nowrap"><%= c.category.name %></td>
                              <td class="text-nowrap"><%= c.created_at.strftime('%d %b %Y') %></td>
                              <td class="text-nowrap">
                                <%= number_to_currency(c.revenue) %>
                              </td>
                              <td class="text-nowrap <%= active_class(c.active) %>">
                                <%= c.active ? 'Active' : 'Inactive' %>
                              </td>
                              <td class="text-nowrap">
                                <%= link_to "Edit Client", edit_client_path(c), class: "btn btn-sm btn-info" %>
                                <%= link_to "Delete Client", c, method: :delete, data: {confirm: 'Are you sure you want to delete this client?'}, class: "btn btn-sm btn-dark text-white"%>
                              </td>
                            </tr>
                            <% end %>
                          <% end %>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>

        <% end %>
          
      </div>
    
  </div>
</div>

app/views/clients/new.html.erb
<div class="row align-items-center pt-5 mt-3">
  <!-- Card START -->
  <div class="col-lg-10 col-xs-12 mx-auto">
    <h1>Clients</h1>
    <p class="mb-4">Let's add a Client.</p>
     
    <div class="card mb-4">
      <div class="card-body">
        <%= form_for @client, html: {class: 'row g-3'} do |f| %>

          <div class="col-md-6">
            <label class="form-label">Client first name</label>
            <%= f.text_field :first_name, autocomplete: 'first-name', class: 'form-control' %>
          </div>

          <div class="col-md-6">
            <label class="form-label">Client last name</label>
            <%= f.text_field :last_name, autocomplete: 'last-name', class: 'form-control' %>
          </div>
          
          <div class="col-md-8">
            <label class="form-label">Client email</label>
            <%= f.text_field :email, autocomplete: 'email', class: 'form-control' %>
          </div>

          <div class="col-md-4">
            <label class="form-label">Select Category</label>
            <%= f.select(:category_id, options_for_select(@categories.map{ |c| [c.name, c.id] }), 
                {:prompt => "Choose Category"}, {class: 'form-select js-choice rounded'}) %>
          </div>

          <div class="col-md-6">
            <label class="form-label">Total Revenue From Client</label>
            <%= f.number_field :revenue, autocomplete: 'revenue', class: 'form-control' %>
          </div>

          <div class="col-md-6 p-2 mr-2 mt-auto">
            <div class="form-check pl-3">
              <%= f.check_box :active, { class: 'form-check-input' } %>
              <label class="form-check-label">
                Activate / Deactivate
              </label>
            </div>
          </div>

          <%= f.submit "Add Client", class: 'btn btn-sm btn-primary mb-0' %>
          
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/clients/search.html.erb
<div class="row pt-5">
  <h1>Search Results</h1>
  <div class="col-12 mb-3">
    <div class="card">
      <div class="card-body bg-light">
        <div class="d-flex bd-highlight">
          <div class="p-2 flex-grow-1 align-self-center">
            <h5 class="text-primary">
              Client Category: <% if @category %> <%= @category.name %> <% end %>
            </h5>
          </div>
          <%= form_tag '', method: :get do %>
            <%= hidden_field_tag "category", @category ? @category.id : '' %>

            <div class="p-2 bd-highlight align-self-center">
              <%= select_tag 'sort', options_for_select(
                [
                  ['Revenue High to Low', 'revenue desc'],
                  ['Revenue Low to High', 'revenue asc'],
                  ['Most Recent Customers', 'clients.created_at desc'],
                  ['Oldest Customers', 'clients.created_at asc'],
                ], selected: @sort
              ), class: "form-select", onchange: "this.form.submit();" %>
            
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="col-lg-3 col-md-12 mb-4">
    <%= form_tag '', class: 'd-flex flex-column p-3 bg-light', method: :get do |f| %>
      
      <%= hidden_field_tag "category", @category ? @category.id : '' %>
      
      <!-- Add sort parameters, because this form is defferent than the sort form above. -->
      <%= hidden_field_tag "sort", @sort %>
      
      <!-- If we have s parameters from the url show that value else show nothing -->
      <%= text_field_tag 's', @s || '', class: 'form-control me-2', placeholder: 'Search by client name' %>
      
      <hr>

      <h5>Search by Revenue</h5>
      <ul class="nav nav-pills flex-column mb-auto">
        <div class="input-group mb-3">
          <span class="input-group-text">$</span>
          <%= number_field_tag 'min', @min || '', class: 'form-control', placeholder: 'Min' %>
        </div>
        <div class="input-group mb-3">
          <span class="input-group-text">$</span>
          <%= number_field_tag 'max', @max || '', class: 'form-control', placeholder: 'Max' %>
        </div>
      </ul>

      <hr>

      <button class="btn btn-secondary mt-2" type="submit">Apply Filters</button>
      
    <% end %>

    <%= form_tag '', method: :get, class: 'd-flex flex-column' do %>
      <button class="btn btn-dark btn-block mt-2" type="submit">Clear All Filters</button>
    <% end %>
    
  </div>
  
  <div class="col-lg-9 col-md-12">
    <div class="card bg-primary">
      <div class="card-header border-0 pb-0">
        <h5 class="card-title text-light">Filter by category</h5>
      </div>
      <%= render "shared/categories" %>
      <%= render partial: "shared/clients", object: @client %>
    </div>
  </div>

</div>

app/views/clients/show.html.erb
<div class="row align-items-center pt-5 pb-5 pb-lg-3 mt-3">
  <!-- Card START -->
  <div class="col-md-8 mx-auto">
    <div class="card bg-primary text-light">
      <div class="card-header">Category: <%= @client.category.name %></div>
      <div class="card-body">
        <h5 class="card-title"><%= client_full_name(@client) %></h5>
        <h6 class="card-subtitle mb-2 text-light"><%= @client.email %></h6>
        <p>Created on: <%= @client.created_at.strftime('%d %b %Y') %></p>
        <%= link_to "Edit Client", edit_client_path(@client), class: "card-link text-white" %>
        <%= link_to "Back to Client Index", clients_path, class: "card-link text-white" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clients</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>

    <%= render "shared/desktop_navbar" %>
    <%= render "shared/notify" %>

    <main>
      <!-- Container START -->
      <div class="container">
        <%= yield %>
      </div>
      
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<h1><%= t('greet') %></h1>

app/views/shared/_categories.html.erb
<nav class="nav border-top border-primary">
  <div class="scrollable-nav">
    <% @categories.each do |c| %>
      <%= link_to "#{c.name}", search_path(category: c.id), class: 'nav-link' %>
    <% end %>
  </div>
</nav>

app/views/shared/_clients.html.erb
<div class="card-body bg-light">
  <div class="table-responsive-lg">
    <table class="table">
      <thead>
        <tr>
          <th class="text-nowrap" scope="col">First Name</th>
          <th class="text-nowrap" scope="col">Last Name</th>
          <th class="text-nowrap" scope="col">Email</th>
          <th class="text-nowrap" scope="col">Category</th>
          <th class="text-nowrap" scope="col">Date Added</th>
          <th class="text-nowrap" scope="col">Total Revenue</th>
          <th class="text-nowrap" scope="col">Status</th>
          <th class="text-nowrap" scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% cache @clients do %>
          <% @clients.each do |c| %>
            <% cache c do %>
            <tr>
              <td class="text-nowrap"><%= link_to c.first_name, client_path(c) %></td>
              
              <td class="text-nowrap"><%= c.last_name %></td>
              <td class="text-nowrap"><%= c.email %></td>
                <td class="text-nowrap"><%= c.category.name %></td>
              <td class="text-nowrap"><%= c.created_at.strftime('%d %b %Y') %></td>
              <td class="text-nowrap">
                <%= number_to_currency(c.revenue) %>
              </td>
              <td class="text-nowrap <%= active_class(c.active) %>">
                <%= c.active ? 'Active' : 'Inactive' %>
              </td>
              <td class="text-nowrap">
                <%= link_to "Edit Client", edit_client_path(c), class: "btn btn-sm btn-info" %>
                <%= link_to "Delete Client", c, method: :delete, data: {confirm: 'Are you sure you want to delete this client?'}, class: "btn btn-sm btn-dark text-white"%>
              </td>
            </tr>
            <% end %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/shared/_desktop_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Client Management</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'All Clients', clients_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Add Clients', new_client_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Search Clients', search_path, class: "nav-link" %>
        </li>

      </ul>

      <div class="d-flex">
        <div class="p-1">
          <%= link_to 'EN', { :locale=>'en' }, class: "btn btn-sm btn-link text-primary" %> |
          <%= link_to 'FR', { :locale=>'fr' }, class: "btn btn-sm btn-link text-primary" %>
        </div>
      </div>


      <ul class="navbar-nav">
        <% if (user_signed_in?) %>
				<!-- Nav right START -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.email %>
          </a>
          <ul id="desktop-user-dropdown" class="dropdown-menu">
            <li>
              <%= link_to '<i class="bi bi-person me-2"></i>Edit Profile'.html_safe, edit_user_registration_path, class: 'dropdown-item' %>
            </li>

            <li><hr class="dropdown-divider"></li>

            <li>
              <%= link_to '<i class="bi bi-box-arrow-in-right me-2"></i>Logout'.html_safe, destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            </li>

          </ul>
        </li>
			<% else %>
				<div class="nav">
					<%= link_to "Login", new_user_session_path, class: "btn btn-link" %>
					<%= link_to "Register", new_user_registration_path, class: "btn btn-link" %>
				</div>
			<% end %>
         
      </ul>
    </div>


  </div>
</nav>

app/views/shared/_notify.html.erb
<% unless flash.empty? %>

  <script type="text/javascript">
    <% flash.each do |msg_key, msg_value| %>

      <% msg_type = msg_key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
      new Noty({
          type: '<%= msg_type %>',
          layout: 'bottomRight',
          timeout: '3000',
          text: '<%= msg_value %>',
          theme: 'sunset'
      }).show();
      
    <% end %>
  </script>
  
<% end %>